"""second update

Revision ID: 467ec8694cdb
Revises: 7fd6ca98ebf3
Create Date: 2023-12-22 01:35:37.615200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467ec8694cdb'
down_revision: Union[str, None] = '7fd6ca98ebf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_day_statistics', sa.Column('stable_diffusion_requests', sa.Integer(), nullable=True))
    op.add_column('user_day_statistics', sa.Column('midjourney_requests', sa.Integer(), nullable=True))
    op.add_column('user_day_statistics', sa.Column('suno_requests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_day_statistics', 'suno_requests')
    op.drop_column('user_day_statistics', 'midjourney_requests')
    op.drop_column('user_day_statistics', 'stable_diffusion_requests')
    # ### end Alembic commands ###
