"""add new fields for leiapix

Revision ID: 70ac19a7a362
Revises: ce5fbf1fb135
Create Date: 2024-01-28 20:41:25.682000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ac19a7a362'
down_revision: Union[str, None] = 'ce5fbf1fb135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_day_statistics', sa.Column('leiapix_requests', sa.Integer(), nullable=True, server_default=sa.text('0')))
    op.add_column('users', sa.Column('available_animation_requests', sa.Integer(), nullable=True, server_default=sa.text('3')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'available_animation_requests')
    op.drop_column('user_day_statistics', 'leiapix_requests')
    # ### end Alembic commands ###
