"""init

Revision ID: 7fd6ca98ebf3
Revises: 
Create Date: 2023-12-09 20:23:52.284000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd6ca98ebf3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=255), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('gpt_version', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('last_message_block', sa.Integer(), nullable=True),
    sa.Column('last_message_date', sa.String(length=255), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_day_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=False),
    sa.Column('gpt_35_requests', sa.Integer(), nullable=True),
    sa.Column('gpt_4_requests', sa.Integer(), nullable=True),
    sa.Column('prodia_requests', sa.Integer(), nullable=True),
    sa.Column('dalle3_requests', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_day_statistics')
    op.drop_table('users')
    op.drop_table('day_statistics')
    # ### end Alembic commands ###
