"""gemini

Revision ID: 8d49b01635d1
Revises: 70ac19a7a362
Create Date: 2024-02-01 21:05:37.690100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d49b01635d1'
down_revision: Union[str, None] = '70ac19a7a362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_day_statistics', sa.Column('gemini_requests', sa.Integer(), nullable=True, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_day_statistics', 'gemini_requests')
    # ### end Alembic commands ###
