"""add leonardo_requests

Revision ID: cc2d716a2b80
Revises: 467ec8694cdb
Create Date: 2023-12-26 01:15:31.682500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2d716a2b80'
down_revision: Union[str, None] = '467ec8694cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_day_statistics', sa.Column('leonardo_requests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_day_statistics', 'leonardo_requests')
    # ### end Alembic commands ###
